Repository apache/myfaces-tobago, pull requests merged in 2020-04, with the labels that each got.

#54 fix: unwanted margin on button icon
  tobago-core/src/main/resources/scss/_tobago.scss
Labels: bug

#55 fix: aria-labelledby for dropdown menus
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/CommandRendererBase.java
Labels: bug

#58 add outline markup for buttons
  tobago-core/src/main/java/org/apache/myfaces/tobago/context/Markup.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/ButtonRenderer.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/renderkit/css/BootstrapClass.java
  tobago-example/tobago-example-demo/src/main/webapp/content/20-component/040-command/00-button+link/button+link.xhtml
Labels: enhancement

#60 update deltaspike in demo to 1.9.3
  tobago-example/tobago-example-demo/pom.xml
Labels: dependencies

#65 fix checkstyle
  tobago-example/tobago-example-demo/src/main/java/org/apache/myfaces/tobago/example/demo/CategoryNode.java
  tobago-example/tobago-example-demo/src/main/java/org/apache/myfaces/tobago/example/demo/SheetController.java
Labels: bug

#67 add a title for date picker button
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/DateRenderer.java
  tobago-core/src/main/resources/org/apache/myfaces/tobago/context/TobagoResourceBundle.properties
  tobago-core/src/main/resources/org/apache/myfaces/tobago/context/TobagoResourceBundle_de.properties
  tobago-core/src/main/resources/org/apache/myfaces/tobago/context/TobagoResourceBundle_es.properties
Labels: enhancement

#71 update toggle, checkbox and radio buttons to Bootstrap 4.2
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/SelectBooleanCheckboxRenderer.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/SelectBooleanToggleRenderer.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/SelectManyCheckboxRenderer.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/SelectOneRadioRenderer.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/renderkit/css/BootstrapClass.java
  tobago-core/src/main/resources/scss/_tobago.scss
Labels: enhancement

#74 fix margin-bottom for custom elements
  tobago-core/src/main/resources/scss/_tobago.scss
Labels: bug

#76 use Bootstrap custom-controls for toggle, checkbox and radio buttons
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/SelectBooleanCheckboxInsideCommandRenderer.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/SelectBooleanCheckboxRenderer.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/SelectBooleanToggleRenderer.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/SelectManyCheckboxInsideCommandRenderer.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/SelectManyCheckboxRenderer.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/SelectOneRadioInsideCommandRenderer.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/SelectOneRadioRenderer.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/renderkit/css/TobagoClass.java
  tobago-core/src/main/resources/scss/_tobago.scss
Labels: enhancement

#79 fix: rendered attribute for composite components in segment layout
  tobago-core/src/main/java/org/apache/myfaces/tobago/util/ComponentUtils.java
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/5500-compositeComponent/Composite_Components.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/5500-compositeComponent/Composite_Components.xhtml
  tobago-example/tobago-example-demo/src/main/webapp/resources/demo-components/inputAsText.xhtml
Labels: bug

#80 fix: rendered attribute for composite components in segment layout
  tobago-core/src/main/java/org/apache/myfaces/tobago/util/ComponentUtils.java
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/5500-compositeComponent/Composite_Components.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/5500-compositeComponent/Composite_Components.xhtml
  tobago-example/tobago-example-demo/src/main/webapp/resources/demo-components/inputAsText.xhtml
Labels: bug

#81 update jsf-development.js
  tobago-theme/tobago-theme-standard/src/main/npm/js/jsf-development.js
  tobago-theme/tobago-theme-standard/src/main/npm/js/jsf-development.js.map
  tobago-theme/tobago-theme-standard/src/main/npm/js/jsf.js
  tobago-theme/tobago-theme-standard/src/main/npm/js/jsf.js.map
Labels: bug

#75 update demo for grid layout and split layout
  tobago-example/tobago-example-demo/src/main/webapp/content/30-concept/16-layout/50-grid/Grid_Layout.xhtml
  tobago-example/tobago-example-demo/src/main/webapp/content/30-concept/16-layout/60-split/Split_Layout.xhtml
Labels: enhancement

#83 chore: update node.js and npm audit
  tobago-theme/pom.xml
  tobago-theme/tobago-theme-charlotteville/src/main/npm/package-lock.json
  tobago-theme/tobago-theme-roxborough/src/main/npm/package-lock.json
  tobago-theme/tobago-theme-scarborough/src/main/npm/package-lock.json
  tobago-theme/tobago-theme-speyside/src/main/npm/package-lock.json
  tobago-theme/tobago-theme-standard/src/main/npm/package-lock.json
  tobago-theme/tobago-theme-standard/src/main/npm/package.json
Labels: dependencies

#82 create jasmine test for behavior
  tobago-example/tobago-example-demo/src/main/webapp/content/30-concept/30-behavior/Behavior.test.js
Labels: enhancement

#84 fix image path in tc:selectManyCheckbox and tc:selectOneRadio
  tobago-example/tobago-example-demo/src/main/webapp/content/20-component/030-select/30-selectOneRadio/Radio.xhtml
  tobago-example/tobago-example-demo/src/main/webapp/content/20-component/030-select/50-selectManyCheckbox/Multi_Checkbox.xhtml
  tobago-example/tobago-example-demo/src/main/webapp/image/EUR-14.png
  tobago-example/tobago-example-demo/src/main/webapp/image/EUR.png
  tobago-example/tobago-example-demo/src/main/webapp/image/JPY-14.png
  tobago-example/tobago-example-demo/src/main/webapp/image/JPY.png
  tobago-example/tobago-example-demo/src/main/webapp/image/TTD-14.png
  tobago-example/tobago-example-demo/src/main/webapp/image/TTD.png
  tobago-example/tobago-example-demo/src/main/webapp/image/USD-14.png
  tobago-example/tobago-example-demo/src/main/webapp/image/USD.png
  tobago-example/tobago-example-demo/src/main/webapp/image/sun-behind-mountains.jpg
Labels: enhancement

#88 improve jasmine test tools
  tobago-example/tobago-example-demo/src/main/java/org/apache/myfaces/tobago/example/demo/SheetSortingController.java
  tobago-example/tobago-example-demo/src/main/webapp/content/20-component/010-input/10-in/In.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/20-component/030-select/30-selectOneRadio/Radio.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/20-component/080-sheet/10-sort/Sheet_Sorting.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/20-component/080-sheet/10-sort/Sheet_Sorting.xhtml
  tobago-example/tobago-example-demo/src/main/webapp/content/30-concept/53-collapsible/00-collapsible-box/Collapsible_Box.test.js
  tobago-example/tobago-example-demo/src/main/webapp/script/tobago-test.js
  tobago-tool/tobago-tool-test/src/main/resources/META-INF/resources/tobago/test/tobago-test-tool.js
Labels: bug, enhancement

#85 feature: Images for Toggles and Checkboxes
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/component/AbstractUISelectBoolean.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/SelectBooleanCheckboxRenderer.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/taglib/component/SelectBooleanCheckboxTagDeclaration.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/taglib/component/SelectBooleanToggleTagDeclaration.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/taglib/component/SelectItemTagDeclaration.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/taglib/component/SelectItemsTagDeclaration.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/taglib/declaration/HasItemImage.java
  tobago-example/tobago-example-demo/src/main/webapp/content/20-component/030-select/10-selectBooleanCheckbox/Checkbox.xhtml
  tobago-example/tobago-example-demo/src/main/webapp/content/20-component/030-select/15-selectBooleanToggle/Toggle.xhtml
Labels: enhancement
