Repository apache/myfaces-tobago, pull requests merged in 2020-05, with the labels that each got.

#90 fix: dynamic IDs in tc:label 'for' attribute
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/component/AbstractUILabel.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/taglib/declaration/HasFor.java
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/1500-output/21-label-for/Label_For.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/1500-output/21-label-for/Label_For.xhtml
Labels: bug

#91 fix: dynamic IDs in tc:label 'for' attribute
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/component/AbstractUILabel.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/taglib/declaration/HasFor.java
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/1500-output/21-label-for/label-for.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/1500-output/21-label-for/label-for.xhtml
Labels: bug

#89 add attribute justify for segment layout
  tobago-core/src/main/java/org/apache/myfaces/tobago/component/Attributes.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/component/AbstractUISegmentLayout.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/SegmentLayoutRenderer.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/taglib/component/SegmentLayoutTagDeclaration.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/layout/SegmentJustify.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/renderkit/css/BootstrapClass.java
  tobago-example/tobago-example-demo/src/main/webapp/content/30-concept/16-layout/30-segment/Segment_Layout.xhtml
  tobago-tool/tobago-tool-apt/src/main/resources/org/apache/myfaces/tobago/apt/component.stg
Labels: enhancement

#92 npm css/ts compiling for development
  tobago-example/tobago-example-demo/pom.xml
  tobago-example/tobago-example-demo/src/main/webapp/content/10-intro/10-getting-started/Getting_Started.xhtml
  tobago-theme/tobago-theme-standard/src/main/npm/dev-rollup.config.js
  tobago-theme/tobago-theme-standard/src/main/npm/dev-tsconfig.json
  tobago-theme/tobago-theme-standard/src/main/npm/package.json
Labels: enhancement

#95 update bootstrap 4.5.0
  tobago-core/src/main/resources/scss/_tobago.scss
  tobago-theme/pom.xml
  tobago-theme/tobago-theme-charlotteville/src/main/npm/package-lock.json
  tobago-theme/tobago-theme-roxborough/src/main/npm/package-lock.json
  tobago-theme/tobago-theme-scarborough/src/main/npm/package-lock.json
  tobago-theme/tobago-theme-speyside/src/main/npm/package-lock.json
  tobago-theme/tobago-theme-standard/src/main/npm/package-lock.json
  tobago-theme/tobago-theme-standard/src/main/npm/package.json
Labels: dependencies

#99 fix unused imports
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/component/AbstractUIFile.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/component/AbstractUIOut.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/component/AbstractUISelectManyCheckbox.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/component/AbstractUISelectManyShuttle.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/component/AbstractUISelectOneRadio.java
Labels: bug

#100 fix: ajax for selectManyCheckbox
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/SelectManyCheckboxRenderer.java
  tobago-example/tobago-example-demo/src/main/webapp/content/20-component/030-select/50-selectManyCheckbox/Multi_Checkbox.xhtml
Labels: bug

#101 set aria roles for header and footer
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/FooterRenderer.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/HeaderRenderer.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/renderkit/html/HtmlRoleValues.java
Labels: enhancement

#102 improve styling for inline radios and checkboxes
  tobago-core/src/main/resources/scss/_tobago.scss
Labels: enhancement

#103 add test for custom elements
  tobago-core/src/main/resources/scss/_tobago.scss
  tobago-core/src/test/java/org/apache/myfaces/tobago/renderkit/html/HtmlElementsUnitTest.java
Labels: enhancement

#104 remove "d-flex" css class
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/FlexLayoutRenderer.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/LabelLayoutRendererBase.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/MessageLayoutRendererBase.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/SplitLayoutRenderer.java
  tobago-core/src/main/resources/scss/_tobago.scss
Labels: enhancement

#105 fix rollup resolve plugin configuration
  tobago-theme/tobago-theme-standard/src/main/npm/dev-rollup.config.js
Labels: bug

#107 tobago-message: custom elements
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/MessagesRenderer.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/renderkit/html/HtmlElements.java
  tobago-example/tobago-example-demo/src/main/webapp/content/30-concept/06-validation/30-messages/Messages.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/30-concept/06-validation/30-messages/Messages.xhtml
  tobago-theme/tobago-theme-standard/src/main/npm/ts/tobago-all.ts
  tobago-theme/tobago-theme-standard/src/main/npm/ts/tobago-messages.ts
Labels: bug

#110 fix: dropdown inStickyHeader() function
  tobago-theme/tobago-theme-standard/src/main/npm/ts/tobago-dropdown.ts
Labels: bug

#109 fix: checkbox/radio buttons in dropdown menus
  tobago-theme/tobago-theme-standard/src/main/npm/ts/tobago-dropdown.ts
Labels: bug

#114 fix: speyside
  tobago-theme/tobago-theme-speyside/src/main/scss/_speyside-overwrites.scss
Labels: bug

#116 rearrange demo layout
  tobago-example/tobago-example-demo/src/main/java/org/apache/myfaces/tobago/example/demo/NavigationState.java
  tobago-example/tobago-example-demo/src/main/webapp/main.xhtml
Labels: enhancement
