Repository apache/myfaces-tobago, pull requests merged in 2020-06, with the labels that each got.

#117 rearrange demo layout: better use of space if browser window is small
  tobago-example/tobago-example-demo/src/main/webapp/main.xhtml
Labels: enhancement

#118 fix: NPE in tobago-tree
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/TreeSelectRenderer.java
Labels: bug

#120 chore: update animal-sniffer-maven-plugin
  pom.xml
Labels: dependencies

#94 create jasmine tests for split layout
  tobago-example/tobago-example-demo/src/main/webapp/content/30-concept/16-layout/60-split/Split_Layout.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/30-concept/16-layout/60-split/Split_Layout.xhtml
Labels: enhancement

#121 tobago-tree: use bootstrap checkbox/radio custom controls
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/TreeSelectRenderer.java
  tobago-core/src/main/resources/scss/_tobago.scss
Labels: enhancement

#125 fix checkstyle
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/TreeListboxRenderer.java
Labels: bug

#127 slightly better naming for setup function of Jasmine test tools
  tobago-tool/tobago-tool-test/src/main/resources/META-INF/resources/tobago/test/tobago-test-tool.js
Labels: enhancement

#126 tobago-tree-listbox: custom elements
  tobago-example/tobago-example-demo/src/main/webapp/content/20-component/090-tree/04-listbox/Tree_Listbox.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/20-component/090-tree/04-listbox/Tree_Listbox.xhtml
  tobago-theme/tobago-theme-standard/src/main/npm/ts/tobago-tree-listbox.ts
Labels: bug
