Repository apache/myfaces-tobago, pull requests merged in 2021-01, with the labels that each got.

#183 integration-tests: add failure details
  tobago-example/tobago-example-demo/src/test/java/org/apache/myfaces/tobago/example/demo/integration/FrontendBase.java
Labels: enhancement

#186 fix: styling for dropdown inside a button group
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/ButtonRenderer.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/CommandRendererBase.java
  tobago-core/src/test/resources/renderer/buttons/separator-inside-buttons.html
Labels: bug

#187 fix: duplicated IDs for SelectBooleanCheckbox/Toggle
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/SelectBooleanRendererBase.java
  tobago-core/src/test/java/org/apache/myfaces/tobago/internal/config/AbstractTobagoTestBase.java
  tobago-core/src/test/java/org/apache/myfaces/tobago/internal/renderkit/renderer/SelectBooleanCheckboxRendererUnitTest.java
  tobago-core/src/test/java/org/apache/myfaces/tobago/internal/renderkit/renderer/SelectBooleanToggleRendererUnitTest.java
  tobago-core/src/test/resources/renderer/selectBooleanCheckbox/selectBooleanCheckboxItemLabel.html
  tobago-core/src/test/resources/renderer/selectBooleanCheckbox/selectBooleanCheckboxLabel.html
  tobago-core/src/test/resources/renderer/selectBooleanToggle/selectBooleanToggleItemLabel.html
  tobago-core/src/test/resources/renderer/selectBooleanToggle/selectBooleanToggleLabel.html
Labels: bug

#192 add comment for dropdown menu
  tobago-theme/tobago-theme-standard/npm/ts/tobago-dropdown.ts
Labels: enhancement

#194 fix: popup jasmine tests
  tobago-example/tobago-example-demo/src/main/webapp/content/20-component/060-popup/Popup.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/20-component/060-popup/Popup.xhtml
Labels: enhancement

#195 fix: jasmine tests
  tobago-example/tobago-example-demo/src/main/webapp/content/20-component/090-tree/00-command/Tree_Command_Types.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/20-component/090-tree/01-select/Tree_Select.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/30-concept/53-collapsible/10-collapsible-popup/Collapsible_Popup.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/35-deprecated/15-suggest-method/Suggest_Method.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/1020-suggest-quotMark/Suggest_QuotMark.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/1040-date/Date.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/1041-date-pattern/Date_Pattern.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/4000-button-link/4050-ajax-dropdown/Ajax_Dropdown.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/4000-button-link/4050-ajax-dropdown/Ajax_Dropdown.xhtml
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/4000-button-link/Button_Link.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/4600-gridLayout/100-auto-column/Auto-Column.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/4600-gridLayout/100-auto-column/Auto-Column.xhtml
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/4600-gridLayout/90-style-tag/Style_Tag.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/4600-gridLayout/90-style-tag/Style_Tag.xhtml
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/4810-labelLayoutTop/LabelLayoutTop.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/4950-severity/Severity.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/50000-java/20-ajax-execute/Ajax_Execute.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/50000-java/20-ajax-execute/Ajax_Execute.xhtml
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/50000-java/30-ajax-special-character/Ajax_Special_Character.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/6000-event/Event.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/6500-behavior/Behavior.test.js
Labels: bug, enhancement

#197 feat: dropdown with selectBooleanToggle
  tobago-core/npm/scss/_tobago.scss
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/CommandRendererBase.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/SelectBooleanToggleRenderer.java
Labels: enhancement

#203 Remove wait cursor (Tobago 2)
  tobago-theme/tobago-theme-scarborough/src/main/resources/org/apache/myfaces/tobago/renderkit/html/scarborough/standard/style/tobago.css
  tobago-theme/tobago-theme-standard/src/main/resources/org/apache/myfaces/tobago/renderkit/html/standard/standard/script/tobago-overlay.js
Labels: bug

#209 fix: qunit tests ware broken, because of different JS init
  tobago-example/tobago-example-demo/src/main/webapp/script/tobago-test.js
Labels: bug

#221 fix: listbox deselection
  tobago-theme/tobago-theme-standard/npm/ts/tobago-select-one-listbox.ts
Labels: bug
