Repository apache/myfaces-tobago, pull requests merged in 2021-02, with the labels that each got.

#222 fix: server sided tab group
  tobago-example/tobago-example-demo/src/main/webapp/content/20-component/070-tab/Tab_Group.test.js
  tobago-theme/tobago-theme-standard/npm/ts/tobago-command.ts
Labels: bug

#219 refactor: Theme Building
  tobago-theme/tobago-theme-standard/npm/package-lock.json
  tobago-theme/tobago-theme-standard/npm/package.json
  tobago-theme/tobago-theme-standard/npm/rollup.config.js
  tobago-theme/tobago-theme-standard/npm/ts/tobago-date.ts
Labels: dependencies

#242 refactor: optimize getter / class structure
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/component/AbstractUICommand.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/component/AbstractUILink.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/CommandRendererBase.java
Labels: enhancement

#305 fix: file upload demo page
  tobago-example/tobago-example-demo/src/main/webapp/content/20-component/100-upload/File_Upload.xhtml
Labels: bug

#312 remove popperJs webjar
  tobago-theme/tobago-theme-standard/pom.xml
Labels: dependencies

#464 fix: suggest
  tobago-core/npm/scss/_tobago.scss
  tobago-theme/tobago-theme-standard/npm/package-lock.json
  tobago-theme/tobago-theme-standard/npm/package.json
  tobago-theme/tobago-theme-standard/npm/ts/tobago-in.ts
  tobago-theme/tobago-theme-standard/npm/ts/tobago-suggest.ts
Labels: bug

#217 fix: styling for dropdown inside input group
  tobago-core/npm/scss/_tobago.scss
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/CommandRendererBase.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/internal/renderkit/renderer/InRenderer.java
  tobago-core/src/main/java/org/apache/myfaces/tobago/renderkit/RendererBase.java
  tobago-core/src/test/resources/renderer/in/input-group-dropdown-after.html
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/40000-style/215-input-group/Group.test.js
  tobago-example/tobago-example-demo/src/main/webapp/content/40-test/40000-style/215-input-group/Group.xhtml
Labels: bug

#549 chore: rebuild themes after dependency updates
  tobago-theme/tobago-theme-standard/npm/dist/js/tobago.js
  tobago-theme/tobago-theme-standard/npm/dist/js/tobago.js.map
Labels: dependencies
